# Select an image from https://hub.docker.com/_/php/.
image: php:8.0

stages:
  - php8-test
  - php7-test

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq

# Install mysql driver
- docker-php-ext-install pdo_mysql
# Install composer
- curl -sS https://getcomposer.org/installer | php
# Install all project dependencies
- php composer.phar install

php8-test:phpunit:  
  image: php:8.0
  script:
  - vendor/bin/phpunit --exclude-group php7only
  allow_failure: true

php8-test:phpstan:  
  image: php:8.0
  script:
  - - vendor/bin/phpstan analyse --error-format=gitlab -c phpstan.neon
  allow_failure: true

php8-test:psalm:  
  image: php:8.0
  script:
  - php vendor/bin/psalm 
  allow_failure: true  


php7-test:phpunit:  
  image: php:7.4
  script:
  - vendor/bin/phpunit --exclude-group php8only
  allow_failure: true

php7-test:phpstan:  
  image: php:7.4
  script:
  - vendor/bin/phpstan analyse --error-format=gitlab -c phpstan-php7.neon
  allow_failure: true  
